spring.application.name=AI-ChatBoot

spring.datasource.url=jdbc:mysql://localhost:3306/ai_agent
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

