package com.day22.java8ProgramsPractice;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

// map() returns a single value for a single input
// only perform the mapping
// map() is used only for transformation

public class FlatStreamTestTwo {

	public static void main(String[] args) {

		ArrayList<String> fruit = new ArrayList<>();
		fruit.add("Apple");
		fruit.add("mango");
		fruit.add("pineapple");
		fruit.add("kiwi");
		fruit.add("Orange");
		fruit.add("Banana");

		System.out.println("List of fruit : " + fruit);

		List list = fruit.stream().map(s -> s.length()).collect(Collectors.toList());

		System.out.println("List generated by map : " + list);

	}
}
